"0","# 単独では呼び出せない"
"0","node_efficiency(g)"
"1","[1m[33mError[39m in `private$check()`:[22m
[38;5;252m[33m![38;5;252m This function should not be called directly[39m
Backtrace:
[90m 1. [39m[1mtidygraph[22m::node_efficiency(g)
[90m 2. [39mtidygraph:::expect_nodes()
[90m 3. [39m.graph_context$free()
[90m 4. [39mself$graph()
[90m 5. [39m[1m[94mprivate$check()[39m[22m
"
